### ISSUE TITLE
Test failure on debian arm64.

### ISSUE THREAD

**Issue by plugwash** [sval-rs/sval#115]
Hi.

The sval crate was recently uploaded to Debian, and our CI infrastructure ran it's tests on a number of architectures. Unfortunately it's failing with.

    test value::owned::tests::owned_value_size ... FAILED
    
    failures:
    
    ---- value::owned::tests::owned_value_size stdout ----
    thread 'value::owned::tests::owned_value_size' panicked at '`OwnedValue` size (48 bytes) is too large (expected up to 40 bytes)
    `Primitive`: 32 bytes
    `TokenKind`: 32 bytes', src/value/owned.rs:913:13
    stack backtrace:
       0: rust_begin_unwind
                 at /usr/src/rustc-1.61.0/library/std/src/panicking.rs:584:5
       1: core::panicking::panic_fmt
                 at /usr/src/rustc-1.61.0/library/core/src/panicking.rs:143:14
       2: sval::value::owned::tests::owned_value_size
                 at ./src/value/owned.rs:913:13
       3: sval::value::owned::tests::owned_value_size::{{closure}}
                 at ./src/value/owned.rs:898:5
       4: core::ops::function::FnOnce::call_once
                 at /usr/src/rustc-1.61.0/library/core/src/ops/function.rs:227:5
       5: core::ops::function::FnOnce::call_once
                 at /usr/src/rustc-1.61.0/library/core/src/ops/function.rs:227:5
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    
    
    failures:
        value::owned::tests::owned_value_size

    test result: FAILED. 51 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

My suspicion is some sort of alignment requirement is making the struct larger, but I don't know exactly what and i'm not really familiar with the constituent types of the structure. I notice that the test already allows a larger size on aarch64 macos, maybe it should allow it on all aarch64 targets.

We are currently using rustc 1.64 I have no idea if that is relavent.

Any advice would be appreciated.

**Comment by KodrAus** [comment]
Sorry for the delay here 🙇 I had a bit of a wild end to the year so am quite behind on things. I've got a PR open in #117  that refactors that code completely out of existence. It's been long enough now that I imagine you've worked around this, but if not I'm happy to ship a quick patch to what's there that fixes that test.

**Comment by plugwash** [comment]
Yeah, I applied https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/sval/debian/patches/arm64-owned-value-size.patch

**Comment by KodrAus** [comment]
Now that `2.x` is published, this issue should be resolved. I'm working on propagating this new release through its dependents (it probably originally came in via `log`).
