### ISSUE TITLE
Stabilize `sval`

### ISSUE THREAD

**Issue by KodrAus** [sval-rs/sval#70]
This issue is a bit of a tracker for a stable release of `sval`. There are a few things to consider first:

- [x] Review the public API. Are there any design decisions there that should be reconsidered?
- [x] Rationalize the current public API. Is there anything there that isn't really necessary for the crate's main use-cases.
- [x] Look at how new features can be introduced (such as new methods to the `Stream` trait, new `Value` implementations) without trending towards API surprises, footguns or inconsistencies.
- [x] Look at some theoretical breaking release strategies that maintain backwards or forwards compatibility.
- [x] Consider making the `serde` feature `serde1` to deal with a possible future version.
- [x] Is the current `error` API based on `impl Error` rather than `dyn Error` the best approach?
- [ ] Make `test::Token` non exhaustive

**Comment by KodrAus** [comment]
With the `0.6` release I’m pretty happy with the shape of the public API and feel like we can confidently make changes to it.

**Comment by KodrAus** [comment]
If we come up with a `serde` layout that looks like:

```rust
pub mod serde {
    pub fn v1 {
        pub fn to_serialize();
        pub fn to_value();
    }
}
```

then we can adjust the `#[derive_from = “serde”]` attribute to provide impls for both `v1` and `v2` if they came about.

**Comment by KodrAus** [comment]
Considering `Error`, it looks like the only useful input type is `dyn Error + 'static`. For callers that can't satisfy that bound, they'll have to use one of `Debug` or `Display`.

**Comment by KodrAus** [comment]
**NOTE:** This will actually need to be released as `2.0.0` instead of `1.0.0` to avoid breaking `log`.

**Comment by KodrAus** [comment]
Actually, we don't need to release as `2.0.0` so long as a final alpha of `value-bag` is released that uses a `=` version requirement on `sval`. That way consumers of `log` won't pull in the breaking `1.0.0` when it comes out.

**Comment by wycats** [comment]
What's the current status of stabilization? I admit to being unable to suss out the status of this crate, but that's perhaps because I haven't found the right documentation yet.

**Comment by KodrAus** [comment]
Hey @wycats! :wave:

No, that's definitely not a "you" problem, I've been quietly working away on this in peripheral places and haven't made any of that work discoverable so far.

The current status of stabilization is that in the process of trying to call this `1.0` along with the announcement of `tokio/valuable` I've re-examined what this crate really _is_. That hasn't changed what the key moving parts are, but has made me want to change the implementation a fair bit. The direction I'm heading in is [over here, towards a generic base that's easy to wrap in an object-safe shell](https://github.com/KodrAus/sval-generic). That repo is still just a sketch, I only made it public a few minutes ago.

Why all the changes? It turns out that with borrowing support this library is effectively a blend of `serde`'s serialize and deserialize APIs into one. Since the API is flat, it's possible to use it as a kind of tokenizer, so you can stream your way through a bit of data and surface its structure, borrowing from the input, as you go. You can do this with `serde`'s deserialize API, but it's quite a lot of machinery (by necessity).

I've moved towards a generic base API because I've found that being bound to trait objects and their runtime costs has prevented me from being able to use this in places where I'd like to. One of those places is in a sparse JSON deserializer that can't accept any unnecessary runtime costs for instance.

So I think stabilization is still a little way off, but am feeling pretty good about the direction things are heading in 🙂
